[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "functions-dist"

[[redirects]]
  from = "/api/config"
  to = "/.netlify/functions/config"
  status = 200

[[redirects]]
  from = "/api/search"
  to = "/.netlify/functions/search"
  status = 200

[[redirects]]
  from = "/api/dispatch"
  to = "/.netlify/functions/dispatch"
  status = 200
